Feature/login-callback
ahachulTeam/ahachul_web pull request #239
Opened 2024-11-03 05:11 UTC by YoonJeongLulu

## What is this PR? 🔍

- **Figma**:
- **Jira Ticket**:
- **기타 참고 문서**:

## Changes 📋

## ScreenShot 📷

## To Reviewers 💬

2024-11-04 03:22 UTC, createhb21 requested changes

2024-11-04 03:22 UTC, createhb21 commented on services/one-app/src/app/api/login/callback/route.ts
> +  } catch (error) {
이런 식으로 에러 케이스를 좀 더 세부적으로 구분하는건 어떨까요?
requestSignIn 에러를 명시적으로 처리할 수 있으니까

```typescript
try {
    const parsedParams = SignInQuerySchema.parse({
      providerType,
      providerCode,
    });

    const res = await requestSignIn(parsedParams);
    const response = NextResponse.json(res);

    if (res.code === APIResponseCode.SUCCESS) {
      const { accessToken, refreshToken } = res.result;

      response.cookies.set(CookieKey.ACCESS_TOKEN, accessToken, {
        sameSite: 'lax',
      });

      response.cookies.set(CookieKey.REFRESH_TOKEN, refreshToken, {
        sameSite: 'lax',
      });

      return NextResponse.redirect(returnTo);
    } else {
      // 로그인 실패 처리
      console.error('Login failed:', res);
      return NextResponse.redirect(`/login?error=true`);
    }
  } catch (error) {
    console.error('Error during sign in:', error);
    // 에러 발생 시 로그인 페이지로 리다이렉트하거나 에러 페이지로 이동
    return NextResponse.redirect(`/login?error=true`);
  }

2024-11-04 03:22 UTC, createhb21 commented on services/one-app/src/app/api/index.ts
> +        if (status === 401) {
Code | Message | HttpStatus
-- | -- | --
200 | 유효하지 않은 ID 토큰입니다. | 400
201 | 유효하지 않은 엑세스 토큰입니다. | 401
202 | 유효기간이 만료된 엑세스 토큰입니다. | 401
203 | 유효하지 않은 리프레쉬 토큰입니다. | 401
204 | 유효기간이 만료된 리프레쉬 토큰입니다. | 401
205 | 유효하지 않은 권한 코드입니다. | 401
206 | 유효하지 않은 액세스 토큰입니다. | 401

저라면 `status === 401` 일때 하기 보다는,
유효기간이 만료된 엑세스 토큰일때(202)만 resetTokenAndRetryRequest를 부를 것 같아요.
이러면 불필요한 네트워크 비용을 야기하니까요

2024-11-04 03:22 UTC, createhb21 commented on services/one-app/src/app/api/index.ts
> +        if (['201', '202', '203', '204', '205'].includes(code)) {
202는 제외

2024-11-04 03:22 UTC, createhb21 commented on services/one-app/src/app/api/util/TokenService.ts
> +export class _TokenService {
`public` 접근 제어자가 없어도 되지 않을까요?

2024-11-04 03:22 UTC, createhb21 commented on services/one-app/src/type/index.ts
`src/model` 으로 옮겨도 될것같아요

2024-11-04 03:22 UTC, createhb21 commented on services/one-app/middleware.ts
`src/middleware` 로 옮기는거 어떤가요?

2024-11-04 05:02 UTC, YoonJeongLulu commented on services/one-app/middleware.ts
nice point! 
app router에서는 app하위에 있어야한다네요! 여기안에 넣겠습니당

2024-11-04 05:03 UTC, YoonJeongLulu commented on services/one-app/middleware.ts
> +  if (!userAgent || isBot(userAgent)) return NextResponse.next();
userAgent는 언제나 조작가능한 값이기에 없거나 봇일 가능성이 있어요!

2024-11-04 05:04 UTC, YoonJeongLulu commented on services/one-app/src/app/api/index.ts
> +        if (status === 401) {
이 경우엔 이게 맞겠네요! 
이번 코드 범위에서 원래 효범님이 작성해두신 로직처리해도 하고
에러 메시지 한번 정리하고나서 또 정리 함 하시죠 ㅎㅎ

2024-11-04 05:05 UTC, YoonJeongLulu commented on services/one-app/src/app/api/util/TokenService.ts
> +export class _TokenService {
맞아요. default가 public이에요.
저는 쓰는 걸 좋아해서 썼는데 안쓰는걸로 통일할까요?

2024-11-04 05:06 UTC, YoonJeongLulu commented on services/one-app/src/app/api/login/callback/route.ts
> +  } catch (error) {
로그인 실패에 따른 페이지를 따로 두는 게 좋겠네요. 그냥 되돌아가면 이상하긴 할듯!

2024-11-04 05:20 UTC, createhb21 approved these changes
👍

2024-11-04 05:20 UTC, createhb21 commented on services/one-app/src/app/api/util/TokenService.ts
> +export class _TokenService {
안쓰는게 좋을듯!

2024-11-04 16:04 UTC, createhb21 commented on services/one-app/src/app/api/login/callback/route.ts
> +  } catch (error) {
@YoonJeongLulu 여기서 실패했으면 홈으로 가죠 그냥 !
그게 나을듯

2024-11-05 12:40 UTC, YoonJeongLulu commented on services/one-app/src/type/index.ts
error쪽은 피쳐 따로 작업 뺄게요! model 폴더 효범쿤꺼 PR 이후로 추가해가면 될 듯합니당

2024-11-05 14:15 UTC, merged