fix: api server side routing -> client side
ahachulTeam/ahachul_web pull request #247
Opened 2024-11-07 13:42 UTC by YoonJeongLulu

## What is this PR? 🔍

- **Figma**:
- **Jira Ticket**:
- **기타 참고 문서**:

## Changes 📋

## ScreenShot 📷

## To Reviewers 💬

2024-11-08 14:10 UTC, YoonJeongLulu commented on services/one-app/src/__test__/1__StartPage.spec.tsx
당장 중요한 테스트가 아니라 skip 합니다.

2024-11-08 14:11 UTC, YoonJeongLulu commented on services/one-app/src/app/(site)/login/callback/page.tsx
> +export default function LoginCallbackPage() {
next.js에서는 useSearchParams을 쓸 때 suspense를 써주어야 하군요.
https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout

2024-11-09 10:23 UTC, createhb21 requested changes

2024-11-09 10:23 UTC, createhb21 commented on services/one-app/src/app/(site)/_component/LoggedIn.tsx
resolveUser 와 같은 과정이 필요하겠군여
nookies까지 저도 한번 검토해보고 다시 논의해봐요.
next-cookies가 비동기로 값을 불러와야한다면 AuthProvider를 하나 감싸도 좋지 않을까 싶어요.

2024-11-09 10:23 UTC, createhb21 commented on services/one-app/src/app/(site)/login/_lib/requestLogin.ts
> +    if (axios.isAxiosError(error)) {
에러 계층 관리 어떤 식으로 하는게 좋은지
윤정님 설계가 기대돼요 ...😋

2024-11-09 10:23 UTC, createhb21 commented on services/one-app/src/app/(site)/login/callback/page.tsx
다음과 같이 분기 처리해보면
추후 에러 로깅을 하는 기간에 좀 더 빠르게 처리 가능할 것 같은데
어떤가요?

```ts
const handleLogin = async () => {
    if (isLoadingRef.current) return

    const providerType = searchParams.get('type')
    const providerCode = searchParams.get('code')

    if (!providerType) {
      router.replace('/login?error=missing_provider_type')
      return
    }

    if (!providerCode) {
      router.replace('/login?error=missing_provider_code')
      return
    }

    if (!isValidSocialSignInType(providerType)) {
      router.replace(`/login?error=invalid_provider_type&type=${providerType}`)
      return
    }

    try {
      isLoadingRef.current = true
      const { result } = await requestLogin({
        providerType: providerType as SocialSignInType,
        providerCode,
      })

      const { accessToken, refreshToken } = result
      AuthService.setToken(accessToken, refreshToken)
      alert('로그인 성공')
      router.replace('/')
    } catch (error) {
      console.error(error)
      alert(error instanceof Error ? error.message : '로그인 중 오류가 발생했습니다')
      router.back()
    } finally {
      isLoadingRef.current = false
    }
  }
```

2024-11-09 10:23 UTC, createhb21 commented on services/one-app/src/app/(site)/login/callback/page.tsx
> +      router.back();
router.back()하면 안되지 않나요?
router.replace('/login?error=api_server_error')
와 같은 곳으로 처리하는게 어떨까요

2024-11-09 10:23 UTC, createhb21 commented on services/one-app/src/app/middleware.ts
> +  if (!AuthService.accessToken || !AuthService.refreshToken) {
middleware의 request에 cookie에 접근할 수 있는 메서드가 존재하는데
이를 사용안하는 이유가 있나요?
조금 .. 계속 헷갈리네요. 
그리고 음 미들웨어에서 AuthService에 올바르게 접근이 되고 있나요?


middleware의 request 이용해서 쿠키 값 읽어오기 ⬇️
ex.
```js
const accessToken = request.cookies.get(AccessToken)
const refreshToken = request.cookies.get(RefreshToken)
```


추가로 앱 라우터에서 이런 Function을 제공하네요.
https://nextjs.org/docs/app/api-reference/functions/cookies

2024-11-09 10:24 UTC, createhb21 commented on services/one-app/src/app/(site)/_component/LoggedIn.tsx
앱 라우터에서 이런 Function을 제공하네요.
https://nextjs.org/docs/app/api-reference/functions/cookies

2024-11-09 12:04 UTC, createhb21 commented on services/one-app/src/app/middleware.ts
> +  if (!AuthService.accessToken || !AuthService.refreshToken) {
그리고 middleware.ts 위치가 src 폴더 바로 아래에 위치해야 작동하는 것 같아요

2024-11-10 04:06 UTC, YoonJeongLulu commented on services/one-app/src/app/(site)/_component/LoggedIn.tsx
비동기로 사용되는 것도 문제가 안된다면 사용 방식을 추가로 검토해볼 필요도 있겠네요!

2024-11-10 04:07 UTC, YoonJeongLulu commented on services/one-app/src/app/(site)/login/callback/page.tsx
좋은 것 같습니다!

2024-11-10 04:08 UTC, YoonJeongLulu commented on services/one-app/src/app/middleware.ts
> +  if (!AuthService.accessToken || !AuthService.refreshToken) {
아 그러네요 ㅋㅋㅋ 제가 안익숙해서 그랬던 것 같아요. 
저렇게 하면 동작에 문제 없을듯합니다. 

middleware옮겼는데 왜 또 여기에 와있지..? 뭔가 바꿨는데 또 바꾸는 느낌이네요 바꿔놓을게요 ㅋㅋㅋㅋ

2024-11-10 05:29 UTC, createhb21 approved these changes
👍

2024-11-10 06:32 UTC, YoonJeongLulu commented on services/one-app/src/app/(site)/login/callback/page.tsx
> +      router.back();
저희 로그인 실패했을 때 에러 페이지 기획이 있었나요?
결국 위 코멘트랑 비슷한 것 같은데 구체화될 때 작업하는 게 어떤가해서욤!

2024-11-10 07:57 UTC, createhb21 commented on services/one-app/src/app/(site)/login/callback/page.tsx
> +      router.back();
@YoonJeongLulu 네네! 
지금은 로그인 에러 페이지는 따로 없이
로그인 페이지로 다시 이동하지만 에러 스낵바를 띄워주기만 하는걸 생각하고있어요

2024-11-10 12:11 UTC, merged