feat: 유실물 글 작성 페이지 기본 UI 구성(일부)
ahachulTeam/ahachul_web pull request #261
Opened 2024-11-20 12:34 UTC by holim0

## What is this PR? 🔍
유실물 글 작성 페이지의 일부 기본 UI를 구성했습니다. 

## ScreenShot 📷

<img width="439" alt="스크린샷 2024-11-20 오후 9 27 27" src="https://github.com/user-attachments/assets/898566e1-4dec-4ab2-b7bf-a4d624e0314d">

## To Reviewers 💬
- `chore: etc work` 메세지의 커밋은 제가 한 작업 사항이 아닌데 들어가 있습니다.(왜 그런가요?)
- 일단 UI를 한 곳에 몰아서 구성을 해둔 상태이고 컴포넌트를 분리하지 못했습니다.
- tailwind를 제대로 써본게 이번에 처음이라 잘 사용했는지 모르겠어요..
- 바텀 시트의 경우 shad/cn을 사용했는데 바텀 시트의 height 조절이 필요합니다.
- react-hook-form을 사용하려고 설치만 해둔 상태입니다.

2024-11-20 13:06 UTC, createhb21 commented
react-hook-form을 꼭 사용해야할지 다른분들 의견이 궁금하긴해요

2024-11-20 13:10 UTC, holim0 commented
일단 없이 적용해보고 불편한 점이 발생했을 때 그걸 해결해줄 수 있는게 react-hook-form이면 그때 가서 적용해도 된다고 생각해요

2024-11-20 14:14 UTC, YoonJeongLulu commented
오 일단 저는 라이브러리 경량화해서 가는 걸 좋아하긴 합니다.
라이브러리가 최적화가 잘되어있는 부분이 있다면 도입 좋은 것 같아요!

2024-11-22 01:02 UTC, createhb21 commented
@holim0 react-hook-form 무난하게 좋긴한데
복잡한 form 형태에서 좀 더 의미있을 것 같아요.
그런데 저희 글작성 스펙은 그렇지 않아서
우선 안사용해도 괜찮지 않을까? 생각들어요.

2024-11-23 04:45 UTC, YoonJeongLulu commented on services/one-app/components.json
이게 어떤거에용?

2024-11-23 08:33 UTC, holim0 commented on services/one-app/components.json
shadcn 사용할 때 추가되는 컴포넌트에 대한 설정 파일이에요.

- 참고: https://ui.shadcn.com/docs/components-json

2024-12-22 12:56 UTC, createhb21 requested changes

2024-12-22 12:56 UTC, createhb21 commented on services/one-app/src/app/(site)/lost-found/_components/LostFoundForm.tsx
> +      const res = await apiClient.post(
useMutation 따로 안쓴 이유가 있을까요 ?

2024-12-22 12:56 UTC, createhb21 commented on services/one-app/src/app/(site)/lost-found/_components/SelectLineDrawer.tsx
> +  const [api, setApi] = useState<CarouselApi>();
오 이거 왜 api라고 하는거에요?

2024-12-22 12:56 UTC, createhb21 commented on services/one-app/src/app/(site)/lost-found/_components/SelectLineDrawer.tsx
> +                            className={`${subwayLineId === line.id ? 'bg-key-color border-key-color text-gray-0' : 'bg-gray-10 border-gray-30 text-gray-90'} w-full flex items-center justify-center ro
cn 쓰면 편할것같아요
utils/cn 에 있어요

```ts
className={cn(
  // 공통
  "w-full flex items-center justify-center rounded-full border px-[4px] py-[8px]",
  "cursor-pointer min-w-[105px] text-label-medium",
  // 조건부
  subwayLineId === line.id
    ? "bg-key-color border-key-color text-gray-0"
    : "bg-gray-10 border-gray-30 text-gray-90"
)}

```

2024-12-22 12:56 UTC, createhb21 commented on services/one-app/src/app/(site)/lost-found/_lib/get.ts
> +export const useGetLostFoundDetail = (id: string) => {
id가 빌 경우가 있어요?

2024-12-22 12:56 UTC, createhb21 commented on services/one-app/src/app/globals.css
> +  .dark {
피그마에 따로 다크모드 없는데
이거 필요한 코드인가요?

2024-12-22 12:56 UTC, createhb21 commented on services/one-app/src/common/components/button.tsx
이 컴포넌트 어디에 쓰이는 컴포넌트인지 알수있을까요?

2024-12-22 12:56 UTC, createhb21 commented on services/one-app/src/common/components/carousel.tsx
위에 버튼이랑 이거 둘다 파일명 파스칼케이스로 부탁드려요!

2024-12-22 12:56 UTC, createhb21 commented on services/one-app/src/lib/utils.ts
src/utils/cn.ts 파일 내용이랑 중복인것같아요

2024-12-22 12:56 UTC, createhb21 commented on services/one-app/src/model/LostFound.ts
> +  images: {
images: DetailImages[]로 하면 되는거 아닌가요?

2024-12-22 12:56 UTC, createhb21 commented on services/one-app/tailwind.config.ts
> +  plugins: [require('tailwindcss-animate')],
이거 쓰고 있는건가요?

2024-12-23 12:16 UTC, holim0 commented on services/one-app/src/app/(site)/lost-found/_components/LostFoundForm.tsx
> +      const res = await apiClient.post(
오 감사합니다. useMutation로 해둘게요!

2024-12-23 12:30 UTC, holim0 commented on services/one-app/src/app/(site)/lost-found/_components/SelectLineDrawer.tsx
> +  const [api, setApi] = useState<CarouselApi>();
타입이 CarouselApi라 크게 고민하지 않고 이름을 지은거 같네요ㅜㅜ 더 명확하게 수정할게요!

2024-12-23 12:36 UTC, holim0 commented on services/one-app/src/common/components/carousel.tsx
네네 저게 shadcn으로 가지고 온 컴포넌트들인데 파스칼로 자동으로 되는지도 알아볼게요!

2024-12-23 12:38 UTC, holim0 commented on services/one-app/src/common/components/button.tsx
저게 지금 shadcn에서 가지고 온 carousel 컴포넌트 내부에서 사용되고 있어요!

https://ui.shadcn.com/docs/components/carousel

실제로 사용되지는 않는 동작이긴 한데 빼는게 좋을까요?

2024-12-23 12:46 UTC, holim0 commented on services/one-app/src/app/(site)/lost-found/_lib/get.ts
> +export const useGetLostFoundDetail = (id: string) => {
지금 LostFoundForm.tsx 컴포넌트를 생성, 수정 페이지에서 공통으로 사용하고 있는데요.

해당 쿼리를 공통으로 가져다 사용하려다보니 lostId 기반으로 분기 처리를 해줬어요.

1. lost-found/create => lostId는 null이기 때문에 쿼리 실행하지 않음
2. lost-found/123/edit => lostId가 null이 아니기 때문에 쿼리 실행

해당 부분 좀 고민이 있었는데 혹시 더 좋은 방법이 있을지 의견이 궁금해요

2024-12-23 13:30 UTC, holim0 commented on services/one-app/src/common/components/button.tsx
일단 carousel 내부에도 안쓰는 컴포넌트 제거하면서 button도 제거하는 쪽으로 작업해볼게요!

2024-12-23 13:31 UTC, createhb21 commented on services/one-app/src/app/(site)/lost-found/_lib/get.ts
> +export const useGetLostFoundDetail = (id: string) => {
enabled 옵션 쓰면 될것같아요!
`enabled: !!id,`

2024-12-23 14:00 UTC, holim0 commented on services/one-app/src/app/(site)/lost-found/_lib/get.ts
> +export const useGetLostFoundDetail = (id: string) => {
useSuspenseQuery에는 enabled 옵션을 제공하지 않더라구요...
https://tanstack.com/query/latest/docs/framework/react/reference/useSuspenseQuery#usesuspensequery

2024-12-23 14:01 UTC, holim0 commented on services/one-app/src/common/components/carousel.tsx
옵션으로 제공해주진 않네요.. 직접 구현해야 하나봅니다

- 참고: https://github.com/shadcn-ui/ui/pull/774#issuecomment-1925431580

2024-12-23 14:02 UTC, holim0 commented on services/one-app/tailwind.config.ts
> +  plugins: [require('tailwindcss-animate')],
사용되지 않아서 제거하겠습니다

2024-12-24 02:11 UTC, createhb21 commented on services/one-app/src/app/(site)/lost-found/_lib/get.ts
> +export const useGetLostFoundDetail = (id: string) => {
@holim0 아 맞네요 !!

```ts
type Mode = 'create' | 'edit';

interface UseLostFoundFormAdapterProps {
  mode: Mode;
  lostId?: string;
}

const DEFAULT_VALUES: LostFoundFormData = {
  title: '',
  initialContent: '',
  subwayLineId: 1,
  lostType: 'LOST',
  images: [],
} as const;

const useLostFoundFormAdapter = ({ mode, lostId }: UseLostFoundFormAdapterProps) => {
  // 수정 모드인데 lostId가 없는 경우에는 에러를 반환한다
  if (mode === 'edit' && !lostId) {
    throw new Error('Edit mode requires lostId');
  }

  if (mode === 'create') {
    return DEFAULT_VALUES;
  }

  // 수정 페이지 에서만 쿼리를 실행한다
  const { data } = useGetLostFoundDetail(lostId!);

  return useMemo(
    () => ({
      title: data.title,
      initialContent: data.content,
      subwayLineId: data.subwayLineId,
      lostType: data.lostType,
      images: data.images.map((image) => ({
        id: image.imageId,
        data: null,
        url: image.imageUrl,
      })),
    }),
    [data],
  );
};
```


이렇게는 어떨까요?

2024-12-24 02:11 UTC, createhb21 commented on services/one-app/src/common/components/carousel.tsx
@holim0 아하 이거 급한건 아니니
우선 백로그로 둬도 좋을것같습니다 🙃

2024-12-24 02:13 UTC, createhb21 approved these changes
[services/one-app/src/app/(site)/lost-found/_lib/get.ts](https://github.com/ahachulTeam/ahachul_web/pull/261/files/947f2939c808054181fcafdf5cf07b122c545568#diff-9f6715ddad2ea3cc07220a4ce3fefb7ce645e5ab878041f4e92efc2baef12e20)
이 부분 커멘트 체크해주시고 CI 성공하게 되면 머지해주세요 🙌

2024-12-24 08:59 UTC, holim0 commented on services/one-app/src/app/(site)/lost-found/_lib/get.ts
> +export const useGetLostFoundDetail = (id: string) => {
@createhb21 mode 없이 lostId 값 유무에 따라 분기 처리하는건 어떻게 생각하시나요?

의도하신바가 path에 edit은 있는데 lostId가 정상적으로 없는 경우까지 생각을 하신거로 보이는데 맞을까요?

mode라는 값이 꼭 있어야할까 생각이 들어서 의견 여쭤봐요!

```ts
const useLostFoundFormAdapter: UseLostFoundFormAdapter = ({ lostId }) => {
  if (!lostId) {
    return DEFAULT_DATA;
  }

  const { data } = useGetLostFoundDetail(lostId);

  const result = useMemo(
    () => ({
      title: data?.title ?? '',
      initialContent: data?.content ?? '',
      subwayLineId: data?.subwayLineId ?? 1,
      lostType: data?.lostType ?? 'LOST',
      images:
        data?.images.map((image) => ({
          id: image.imageId ?? null,
          data: null,
          url: image.imageUrl,
        })) ?? [],
    }),
    [data],
  );
  return result;
};
```

2024-12-24 10:20 UTC, createhb21 commented on services/one-app/src/app/(site)/lost-found/_lib/get.ts
> +export const useGetLostFoundDetail = (id: string) => {
@holim0 넵 좋습니다 🙃

2024-12-26 09:42 UTC, holim0 commented on services/one-app/src/app/(site)/lost-found/_lib/get.ts
> +export const useGetLostFoundDetail = (id: string) => {
@createhb21 이게 또 근데 hook이 조건부로 호출되면 안된다는 eslint 룰에 위반이 되네요..

2024-12-26 11:02 UTC, holim0 commented on services/one-app/src/app/(site)/lost-found/_lib/get.ts
> +export const useGetLostFoundDetail = (id: string) => {
@createhb21 아예 독립적인 컴포넌트로 분리했는데 리뷰 부탁드려요!

2024-12-26 14:58 UTC, createhb21 commented on services/one-app/src/app/(site)/lost-found/_lib/get.ts
> +export const useGetLostFoundDetail = (id: string) => {
@createhb21 👍👍

2025-01-07 11:06 UTC, merged